// ═══════════════════════════════════════
// DATA
// ═══════════════════════════════════════
const MENU = [
  // ── POPULAR (top 5 from reviews)
  {id:1,cat:'popular',emoji:'🥘',name:'Cheese Kala Pav Bhaji',desc:'Bombay-style black bhaji of mashed potatoes, tomatoes & veggies topped with generous melted cheese and butter. Every reviewer mentions this.',price:219,spice:2,tags:['pop'],available:true},
  {id:2,cat:'popular',emoji:'🍢',name:'Paneer Tikka',desc:'Cottage cheese cubes marinated in tandoori masala, cooked in the tandoor until perfectly charred. A timeless classic that never disappoints.',price:299,spice:2,tags:['pop'],available:true},
  {id:3,cat:'popular',emoji:'🌯',name:'Tandoori Cigars',desc:'Roomali roti stuffed with spinach and cheese, smoked and rolled into crispy cigars. Guests rave about these every visit.',price:229,spice:1,tags:['pop'],available:true},
  {id:4,cat:'popular',emoji:'🍛',name:'Dal Makhani',desc:'Rich, creamy Delhi-style dal makhani slow-cooked with charcoal smoke. Reviewers consistently call it one of the best in Bengaluru.',price:299,spice:1,tags:['pop'],available:true},
  {id:5,cat:'popular',emoji:'🍫',name:'Death By Chocolate Sundae',desc:'The ultimate chocolate indulgence — layers of chocolate ice cream, hot fudge, brownie bits and chocolate sauce. A must-try finish.',price:349,spice:0,tags:['pop'],available:true},
  // ── CHAAT & STREET FOOD
  {id:6,cat:'chaat',emoji:'💧',name:'Khatta Meetha Paani Poori',desc:'Crispy Bombay puri stuffed with boiled peas, potato and onion in our signature sweet-tangy-spicy water.',price:149,spice:2,tags:['pop'],available:true},
  {id:7,cat:'chaat',emoji:'🥙',name:'Kala Pav Bhaji',desc:'Bombay-style black bhaji of mashed potatoes, tomatoes and vegetables served with soft butter pav.',price:189,spice:2,tags:[],available:true},
  {id:8,cat:'chaat',emoji:'🧆',name:'Ragada Patties',desc:'Pan-fried potato patties served with a spicy chickpea gravy, chutneys and sev.',price:169,spice:2,tags:[],available:true},
  {id:9,cat:'chaat',emoji:'🥗',name:'Dahi Papdi',desc:'Crispy puris topped with boiled chickpeas, potatoes, sweet curd, tamarind and mint chutneys.',price:149,spice:1,tags:[],available:true},
  {id:10,cat:'chaat',emoji:'🌶️',name:'Raj Kachori',desc:'Large crispy puri stuffed with dal, topped with yogurt, pomegranate, sev and chutneys.',price:179,spice:2,tags:[],available:true},
  {id:11,cat:'chaat',emoji:'🍚',name:'Bombay Bhel',desc:'Classic Mumbai street snack — puffed rice tossed with vegetables, chutneys and spices.',price:129,spice:2,tags:[],available:true},
  {id:12,cat:'chaat',emoji:'🥔',name:'Aloo Tikki Chaat',desc:'Crunchy potato tikkis served with roasted chana dal, yogurt, and house spices.',price:159,spice:2,tags:[],available:true},
  {id:13,cat:'chaat',emoji:'🌿',name:'Palak Papadi Chaat',desc:'Fried spinach leaves with sweet curd, potatoes, boondi, sev and chutney drizzle.',price:169,spice:1,tags:['new'],available:true},
  {id:14,cat:'chaat',emoji:'🥙',name:'Samosa Chole Di',desc:'Crispy samosas served on a bed of spicy chickpea curry with green chutney.',price:149,spice:3,tags:[],available:true},
  {id:15,cat:'chaat',emoji:'🍱',name:'Bombay Tawa Pulao',desc:'Chowpati-style rice cooked with masala veggies, butter and a generous squeeze of lemon.',price:189,spice:2,tags:[],available:true},
  // ── STARTERS
  {id:16,cat:'starters',emoji:'🍢',name:'Paneer Green Mojo Bites',desc:'Crisp paneer bites coated in spinach pesto sauce — light, herby and addictive.',price:249,spice:1,tags:['pop'],available:true},
  {id:17,cat:'starters',emoji:'🌿',name:'Broccoli Tikka',desc:'Marinated broccoli cooked in a tandoor, topped with cheese. A healthy, smoky delight.',price:269,spice:1,tags:['new'],available:true},
  {id:18,cat:'starters',emoji:'🍍',name:'Tandoori Pineapple',desc:'Pineapple cubes marinated in peri peri masala and cooked in the tandoor. Sweet meets smoky.',price:219,spice:2,tags:[],available:true},
  {id:19,cat:'starters',emoji:'🧀',name:'Cheesey Globe-Joc',desc:'Jalapeño cheese balls served with house cheese sauce and fresh salsa.',price:269,spice:2,tags:[],available:true},
  {id:20,cat:'starters',emoji:'🫙',name:'Hummus And Pita',desc:'House-made pita bread served with a variety of classic hummus — creamy, smoky and roasted garlic.',price:249,spice:0,tags:[],available:true},
  {id:21,cat:'starters',emoji:'🧆',name:'Sadak Chaap Sliders',desc:'Cheese-filled soya chaap patty sliders with house salad and crispy fries.',price:289,spice:2,tags:['pop'],available:true},
  {id:22,cat:'starters',emoji:'🍅',name:'3rd Century Bruschetta',desc:'Paneer bhurji served over crisp French loaf slices with balsamic vinegar and herbs.',price:229,spice:1,tags:[],available:true},
  {id:23,cat:'starters',emoji:'🌶️',name:'Paneer Chatori Bites',desc:'Paneer bites tossed in a desi chilli sauce — spicy, tangy and impossible to stop eating.',price:249,spice:3,tags:[],available:true},
  {id:24,cat:'starters',emoji:'🌿',name:'Paneer Kariyapak',desc:'Paneer bites tossed in Karnataka-style pepper masala — a local favourite.',price:259,spice:2,tags:[],available:true},
  {id:25,cat:'starters',emoji:'🥟',name:'Schezwan Cocktail Samosa',desc:'Mini samosas stuffed with Schezwan-style veggies, served with dipping sauce.',price:179,spice:2,tags:[],available:true},
  {id:26,cat:'starters',emoji:'🧀',name:'Annas Roast Paneer',desc:'Paneer bites roasted in Karavali-style ghee masala — rich, coastal and deeply flavourful.',price:269,spice:2,tags:[],available:true},
  // ── SOUPS
  {id:27,cat:'soups',emoji:'🍲',name:'Wild Mushroom & Sweet Potato Soup',desc:'Comforting soup made from farm mushrooms and roasted sweet potatoes. Thick, earthy and warming.',price:179,spice:0,tags:['pop'],available:true},
  {id:28,cat:'soups',emoji:'🥣',name:'Roast Garlic Tomato Tang',desc:'Creamy tomato soup simmered with roasted garlic, served with nachos on the side.',price:169,spice:1,tags:[],available:true},
  {id:29,cat:'soups',emoji:'🥟',name:'Crisp Dumpling In A Well',desc:'Chinese-style clear soup with crisp vegetable dumplings floating in a delicate broth.',price:189,spice:1,tags:[],available:true},
  {id:30,cat:'soups',emoji:'🍜',name:"Mama Chow Chow",desc:'Hot and spicy Chinese-style soup topped with crispy vegetables and noodles.',price:179,spice:2,tags:[],available:true},
  {id:31,cat:'soups',emoji:'🍜',name:"Chao's Lung Fung",desc:'A clear soup loaded with Chinese vegetables and noodles — light yet satisfying.',price:169,spice:1,tags:[],available:true},
  // ── CURRIES & MAINS
  {id:32,cat:'mains',emoji:'🍛',name:'Paneer Tikka Masala',desc:'Smoky marinated paneer cooked in rich tikka masala gravy — a timeless Punjabi classic.',price:329,spice:2,tags:['pop'],available:true},
  {id:33,cat:'mains',emoji:'🥘',name:'Dal Makhani',desc:'Rich, creamy Delhi-style dal makhani smoked with charcoal — our most-praised curry.',price:299,spice:1,tags:['pop'],available:true},
  {id:34,cat:'mains',emoji:'🌿',name:'TBC Special Methi Malai Paneer',desc:'Cottage cheese cooked in methi leaves and butter gravy — indulgent and aromatic.',price:349,spice:1,tags:['new'],available:true},
  {id:35,cat:'mains',emoji:'🍲',name:'Lasooni Tikka Masala',desc:'Paneer tikka flavoured with garlic and cooked in rich onion gravy. Garlic lovers rejoice.',price:339,spice:2,tags:[],available:true},
  {id:36,cat:'mains',emoji:'🥘',name:'Pahadi Kofta',desc:'Mix vegetable koftas cooked in a creamy malai gravy — mellow, rich and satisfying.',price:319,spice:1,tags:[],available:true},
  {id:37,cat:'mains',emoji:'🥬',name:'Broccoli Saag',desc:'Broccoli cooked to a saag consistency with triple tempering and hours of simmering.',price:299,spice:1,tags:[],available:true},
  {id:38,cat:'mains',emoji:'🍛',name:'Paneer Butter Masala',desc:'Paneer cooked in a rich, smoky butter gravy. Classic, comforting and always a crowd-pleaser.',price:329,spice:1,tags:[],available:true},
  {id:39,cat:'mains',emoji:'🌾',name:'Infused Kofta',desc:'Spinach koftas infused with hay and rosewood, served with Punjabi-style saag.',price:309,spice:1,tags:[],available:true},
  {id:40,cat:'mains',emoji:'🥘',name:'Peshawari Kofta',desc:'Cashew-coated koftas served in a rich almond and cashew gravy — Frontier-style luxury.',price:349,spice:1,tags:[],available:true},
  {id:41,cat:'mains',emoji:'🍛',name:'Dal Tadka',desc:'A blend of three lentils tempered twice for a smoky, deeply flavourful finish.',price:249,spice:1,tags:[],available:true},
  {id:42,cat:'mains',emoji:'🫑',name:'Kadhai Paneer',desc:'Paneer cubes in a spicy kadhai masala with home-blended spices and bell peppers.',price:329,spice:2,tags:[],available:true},
  {id:43,cat:'mains',emoji:'🍅',name:'Paneer Takatak',desc:'Tangy paneer with chopped bell peppers and cheese, cooked on a tawa.',price:319,spice:2,tags:[],available:true},
  {id:44,cat:'mains',emoji:'🌿',name:'Hansa Ben Ki Subzi',desc:'Mughal-style achari-flavoured vegetables — a unique, fragrant preparation.',price:289,spice:2,tags:[],available:true},
  {id:45,cat:'mains',emoji:'🍅',name:'Sev Tomato Ni Sabji',desc:'Gujarati-style tomato-based dish with crispy aloo sev — sweet, tangy and comforting.',price:259,spice:1,tags:[],available:true},
  // ── RICE, BIRYANI & NOODLES
  {id:46,cat:'rice',emoji:'🍚',name:'Awad Ki Shaan Biryani',desc:'Flavorful basmati rice cooked with vegetables and green masala in the Awadhi dum style.',price:329,spice:2,tags:['pop'],available:true},
  {id:47,cat:'rice',emoji:'🥘',name:'Shashlik Paneer Biryani',desc:'Royal biryani with paneer shashlik from the kitchens of the Maharajas — rich and aromatic.',price:369,spice:2,tags:[],available:true},
  {id:48,cat:'rice',emoji:'🍄',name:'Yakhni Mushroom Biryani',desc:'Dum biryani with mushrooms in a yogurt and chilli base — lighter, fragrant and delicious.',price:329,spice:2,tags:[],available:true},
  {id:49,cat:'rice',emoji:'🌿',name:'Subz Handi Biryani',desc:'Kashmiri-style mixed veg biryani, cooked in saffron stock for a subtle floral aroma.',price:319,spice:1,tags:[],available:true},
  {id:50,cat:'rice',emoji:'🍚',name:'Kaju Jeera Ghee Rice',desc:'Basmati rice cooked with ghee, cumin and dry fruits — aromatic and comforting.',price:229,spice:0,tags:[],available:true},
  {id:51,cat:'rice',emoji:'🥘',name:'Punjabi Kadhi Rice Bowl',desc:'Tangy Punjabi kadhi with soft pakoras, served over steamed rice.',price:269,spice:1,tags:[],available:true},
  {id:52,cat:'rice',emoji:'🍛',name:'Thai Curry Rice',desc:'Rich Thai-style green or red curry served over steamed rice — aromatic and creamy.',price:299,spice:2,tags:[],available:true},
  {id:53,cat:'rice',emoji:'🍚',name:'Classic Schezwan Fried Rice',desc:'Wok-tossed Schezwan fried rice paired with spicy chilli paneer bites.',price:269,spice:3,tags:[],available:true},
  {id:54,cat:'rice',emoji:'🔥',name:'Chin Chu Chi Garlic Rice',desc:'Fried rice flavoured with burnt garlic and chillies — bold, smoky and addictive.',price:259,spice:2,tags:[],available:true},
  {id:55,cat:'rice',emoji:'🍜',name:'Sakath Basil Noodles',desc:'Spicy noodles tossed in a tangy chilli-basil sauce — Thai-inspired and fiery.',price:259,spice:3,tags:[],available:true},
  {id:56,cat:'rice',emoji:'🍄',name:'Sticky Garlic & Mushroom Noodles',desc:'Authentic sticky noodles tossed in a savory mushroom and garlic sauce.',price:269,spice:1,tags:[],available:true},
  {id:57,cat:'rice',emoji:'🌶️',name:'Tai Pai Noodles',desc:'Noodles in a spicy chilli sauce with cashews, peanuts and cottage cheese.',price:269,spice:3,tags:[],available:true},
  {id:58,cat:'rice',emoji:'🍚',name:'De Tadke Pe Tadka Fried Rice',desc:'Extra flavourful fried rice double-tempered and topped with crispy noodles.',price:259,spice:2,tags:[],available:true},
  // ── WOOD FIRE PIZZA
  {id:59,cat:'pizza',emoji:'🍕',name:'Margherita Classic',desc:'Classic Neapolitan pizza topped with fresh basil and melted mozzarella. Simple perfection.',price:349,spice:0,tags:[],available:true},
  {id:60,cat:'pizza',emoji:'🧀',name:'BBQ Paneer Pizza',desc:'BBQ marinated paneer over cheese and pesto base — smoky, tangy and satisfying.',price:399,spice:1,tags:['pop'],available:true},
  {id:61,cat:'pizza',emoji:'🌿',name:'Basil Pesto & Cherry Tomatoes',desc:'Neapolitan pizza with house basil pesto and fresh cherry tomatoes.',price:379,spice:0,tags:[],available:true},
  {id:62,cat:'pizza',emoji:'🍕',name:'Paneer Tikka Masala Pizza',desc:'Pizza with flavorful Indian-style paneer tikka — the ultimate east-meets-west.',price:399,spice:2,tags:[],available:true},
  {id:63,cat:'pizza',emoji:'🧄',name:'Crispy Garlic Pizza',desc:'Pizza topped with olive oil, garlic paste, parmesan and oregano. A garlic lover\'s dream.',price:349,spice:1,tags:[],available:true},
  {id:64,cat:'pizza',emoji:'🌽',name:'Roast Zucchini & Corn',desc:'Pizza topped with roasted zucchini, sweet corn and mozzarella.',price:369,spice:0,tags:[],available:true},
  {id:65,cat:'pizza',emoji:'🫒',name:'Chickpeas Olive Pizza',desc:'Pizza with marinated chickpeas and fresh olives — Mediterranean and light.',price:379,spice:0,tags:[],available:true},
  {id:66,cat:'pizza',emoji:'🍅',name:'Farmhouse & Spiced Tomato',desc:'House special tomato pizza with cubes of seasonal veggies.',price:369,spice:1,tags:[],available:true},
  {id:67,cat:'pizza',emoji:'🌿',name:'Tandoori Veggies Pizza',desc:'Pizza with clay oven-cooked veggies for a smoky Indian twist.',price:389,spice:2,tags:[],available:true},
  {id:68,cat:'pizza',emoji:'🥗',name:'Balsamic & Shaved Parmesan',desc:'Pizza topped with rocket leaves, balsamic reduction and parmesan shavings.',price:399,spice:0,tags:['new'],available:true},
  {id:69,cat:'pizza',emoji:'🍕',name:'King Nugget',desc:'Soya nuggets spiced with Italian herbs and Indian sauce on a pizza base.',price:379,spice:2,tags:[],available:true},
  {id:70,cat:'pizza',emoji:'🥪',name:'Pizza Sandwich',desc:'A twist on pizza — stuffed with exotic veggies in a folded crust.',price:349,spice:1,tags:[],available:true},
  // ── PASTA
  {id:71,cat:'pasta',emoji:'🍝',name:'Arrabiata Penne',desc:'Penne pasta in a spicy tomato-based sauce with fresh basil and capers.',price:279,spice:3,tags:['pop'],available:true},
  {id:72,cat:'pasta',emoji:'🧄',name:'Aglio Olio',desc:'Spaghetti tossed in virgin olive oil with garlic and herbs — simple, pure and perfect.',price:269,spice:1,tags:[],available:true},
  {id:73,cat:'pasta',emoji:'🌿',name:'Basil Pesto Pasta',desc:'Freshly ground pesto tossed with your choice of pasta and parmesan.',price:289,spice:0,tags:[],available:true},
  {id:74,cat:'pasta',emoji:'🍄',name:'Mushroom & Spinach Cream',desc:'Creamy pasta with hand-picked mushrooms and spinach in a rich white sauce.',price:299,spice:0,tags:[],available:true},
  {id:75,cat:'pasta',emoji:'🧀',name:'Triple Cheese Penne',desc:'Rich pasta cooked in a creamy white sauce with three kinds of melted cheese.',price:319,spice:0,tags:[],available:true},
  {id:76,cat:'pasta',emoji:'🌶️',name:'Dil Hai Hindustani',desc:'Spaghetti with Indian spices and herbs in a creamy sauce — fusion done right.',price:289,spice:2,tags:[],available:true},
  {id:77,cat:'pasta',emoji:'💜',name:'Gulabi Aankhee',desc:'Pasta cooked in a unique house-made purple sauce — as beautiful as it tastes.',price:299,spice:0,tags:['new'],available:true},
  {id:78,cat:'pasta',emoji:'🥗',name:'Swedish Veg Balls Pasta',desc:'Pasta in tomato sauce served with vegetable balls and rocket herbs.',price:289,spice:1,tags:[],available:true},
  // ── BREADS
  {id:79,cat:'breads',emoji:'🫓',name:'TBC Butter Naan',desc:'Soft naan brushed with house-blend butter. Our most-ordered bread — unmistakably good.',price:89,spice:0,tags:['pop'],available:true},
  {id:80,cat:'breads',emoji:'🧀',name:'Cheese Chilli Naan',desc:'Soft naan stuffed with cheese and green chillies for a spicy, melty kick.',price:129,spice:2,tags:[],available:true},
  {id:81,cat:'breads',emoji:'🧄',name:'Garlic Naan',desc:'Classic naan infused with roasted garlic — the perfect companion to any curry.',price:99,spice:0,tags:[],available:true},
  {id:82,cat:'breads',emoji:'🫓',name:'Chur Chur Naan',desc:'Crispy, flaky naan with a delicious buttery texture — Amritsari style.',price:119,spice:0,tags:[],available:true},
  {id:83,cat:'breads',emoji:'🌶️',name:'Mirchi Lasoon Paratha',desc:'Paratha spiced with green chillies and garlic for a fiery, flavourful breakfast.',price:109,spice:3,tags:[],available:true},
  {id:84,cat:'breads',emoji:'🫓',name:'Amritsari Gali Kulcha',desc:'Traditional Amritsari kulchas with a perfect blend of spices and soft texture.',price:129,spice:1,tags:[],available:true},
  {id:85,cat:'breads',emoji:'🫓',name:'Siddu Paaji Da Paratha',desc:'Rich, spicy paratha inspired by the Punjabi roadside dhaba experience.',price:119,spice:2,tags:[],available:true},
  {id:86,cat:'breads',emoji:'🧀',name:'Cheesy Bellpepper Naan',desc:'Naan filled with cheese and flavourful bell peppers — soft, gooey and delicious.',price:139,spice:0,tags:[],available:true},
  {id:87,cat:'breads',emoji:'🌿',name:'Pudina Ka Thanda Paratha',desc:'Refreshing mint-flavoured paratha — aromatic and cooling.',price:99,spice:0,tags:[],available:true},
  {id:88,cat:'breads',emoji:'🫓',name:'Naan Tikona',desc:'Unique triangular naan, soft and fluffy — great for scooping curries.',price:89,spice:0,tags:[],available:true},
  {id:89,cat:'breads',emoji:'🫓',name:'Kakke Di Roti',desc:'Traditional wholesome roti — plain or with a generous dollop of butter.',price:59,spice:0,tags:[],available:true},
  {id:90,cat:'breads',emoji:'🥙',name:'Lachha Paratha',desc:'Multi-layered flaky paratha with crispy edges and a soft, buttery center.',price:89,spice:0,tags:[],available:true},
  // ── DESSERTS
  {id:91,cat:'desserts',emoji:'🍫',name:'Death By Chocolate',desc:'The ultimate chocolate indulgence — chocolate ice cream, hot fudge, brownie and chocolate sauce.',price:349,spice:0,tags:['pop'],available:true},
  {id:92,cat:'desserts',emoji:'🍮',name:"Mini Mama's Broken Tart",desc:'Honey & fig ice cream with tart, oatmeal biscuits, crushed pistachio and mango jelly.',price:299,spice:0,tags:['pop'],available:true},
  {id:93,cat:'desserts',emoji:'🍪',name:'Mini Nutella Baked Cookies',desc:'Belgian ice cream with Nutella cookies, chocolate cake and roasted nuts.',price:329,spice:0,tags:[],available:true},
  {id:94,cat:'desserts',emoji:'🍓',name:'Lucifer\'s Sin',desc:'Vanilla ice cream, red velvet cake and chocolate sauce — dangerously good.',price:319,spice:0,tags:[],available:true},
  {id:95,cat:'desserts',emoji:'🍫',name:'Chocolate Brownie Fudge',desc:'Rich, indulgent warm brownie fudge — a classic for good reason.',price:279,spice:0,tags:[],available:true},
  {id:96,cat:'desserts',emoji:'☕',name:'Tiramisu',desc:'Classic Italian tiramisu — coffee-soaked ladyfingers with mascarpone and cocoa.',price:299,spice:0,tags:[],available:true},
  {id:97,cat:'desserts',emoji:'🍈',name:'Lychee Sundae',desc:'Vanilla ice cream with lychees, dry fruits and whipped cream.',price:249,spice:0,tags:[],available:true},
  {id:98,cat:'desserts',emoji:'🎂',name:'Mini Cake Fudge',desc:'Vanilla ice cream with vanilla muffins, dark and white chocolate sauce.',price:269,spice:0,tags:[],available:true},
  {id:99,cat:'desserts',emoji:'🍦',name:'Belgium Chocolate Ice Cream',desc:'Rich, creamy Belgian chocolate ice cream — pure indulgence in a scoop.',price:149,spice:0,tags:[],available:true},
  {id:100,cat:'desserts',emoji:'🍦',name:'Butterscotch Ice Cream',desc:'Classic butterscotch with caramel swirls — sweet, creamy and nostalgic.',price:129,spice:0,tags:[],available:true},
  {id:101,cat:'desserts',emoji:'🍦',name:'Mango Ice Cream',desc:'Seasonal mango ice cream — bright, fruity and refreshing.',price:129,spice:0,tags:[],available:true},
  {id:102,cat:'desserts',emoji:'🍦',name:'Paan Ice Cream',desc:'Unique paan-flavoured ice cream — a beloved Indian palate cleanser.',price:139,spice:0,tags:['new'],available:true},
  {id:103,cat:'desserts',emoji:'🍦',name:'Fig & Honey Ice Cream',desc:'Delicate fig and honey ice cream — subtle, refined and beautiful.',price:149,spice:0,tags:[],available:true},
];

const REVIEWS_DATA = [
  {name:'Mythri Channamalladevaru',meta:'Local Guide · 47 reviews',rating:3,text:'Visited The Bangalore Cafe — the ambience is lovely and food is unique. Ordered Sadak Chaap Sliders and Teriyaki Butter Garlic Sizzler. A bit premium for the portions, but the flavours are genuinely creative.',date:'3 weeks ago',avatar:'M',color:'#E8630A'},
  {name:'Udit Kansal',meta:'Local Guide · 396 reviews',rating:5,text:'Great variety of fusion dishes — enjoyed everything we ordered! Mojo Bites (Pesto Mushroom) and Shukla Ki Potli were absolute highlights. The staff was warm and attentive throughout.',date:'1 month ago',avatar:'U',color:'#2D6A4F'},
  {name:'Poornima Kadam S.',meta:'Local Guide · 37 reviews',rating:5,text:'Food is 5/5 delicious. The ambience is great and service was remarkable. Special shoutout to Umesh — his presence of mind and service manners made our anniversary dinner truly special!',date:'2 months ago',avatar:'P',color:'#C75B7A'},
  {name:'Rahul Mehta',meta:'Local Guide · 89 reviews',rating:4,text:'Came for a team lunch and everyone loved it. The Blue Mocha is absolutely stunning to look at and even better to taste. Pav Bhaji with the kala masala is genuinely next level.',date:'2 months ago',avatar:'R',color:'#7B4F2E'},
  {name:'Sneha Iyer',meta:'22 reviews',rating:5,text:'Celebrated my birthday here and the team made it so special. The Rasmalai Tres Leches is divine — unlike anything I have had before. Will definitely be back for date nights!',date:'3 months ago',avatar:'S',color:'#D4AF37'},
  {name:'Karthik B.',meta:'Local Guide · 156 reviews',rating:4,text:'Solid menu with interesting fusion choices. The spring rolls and dal makhani combo is a winner. Service is quick and the interiors feel warm and inviting. Recommended for family dinners.',date:'3 months ago',avatar:'K',color:'#4A90D9'},
];

let userReviews = [];
let selectedStars = 0;
let menuAvailability = {};
MENU.forEach(i => menuAvailability[i.id] = i.available);

